### ISSUE TITLE
add provenance use cases

### ISSUE THREAD

**Issue by mgalster** [veracitylab/provenance-demonstrator-openmrs#9]
Since the focus of the demonstrator is provenance, I wonder if there could be another page explicitly discussing this. There is already a section in the top-level Readme.md. Maybe this could be enhanced with a couple of explicit provenance use cases or scenarios, e.g., why is a health warning shown, based on what data is the warning shown, etc.

**Comment by jensdietrich** [comment]
This is basically one use case (potentially with multiple actors) -- user inspects / tries to understand a flag in order to take action. At the moment their is some rudimentary support for this -- the flag has an associated description. This is short and has to be kept consistent with the semantics (=conditions defining) of the flag. A better way would be for instance to use a proper rule engine (or some other form of inference), and to generate the description on the fly.

**Comment by tranngan552** [comment]
Added a folder for provenance use cases and links on top level README.md:
- provenance-scenario.md: Introduce provenance features
- provenance-inspection.md: a scenario when users try to understand the alert message appearing on the patient dashboard.
